name = "event-app-backend"
main = "src/lib.rs"
compatibility_date = "2024-04-03"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "event-app-db"
database_id = "01863c26-df21-4b99-98f7-c172c693473e"

[build]
command = "worker-build --release"
